app/cf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("clients.urls", namespace="clients")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/clients/urls.py
from django.urls import path

from . import views

app_name = "clients"


urlpatterns = [
    path("", views.ClientListView.as_view(), name="client-list"),
    path("client/<int:pk>/", views.ClientDetailView.as_view(), name="client-detail"),
    path(
        "client/update/<int:pk>/",
        views.ClientUpdateView.as_view(),
        name="client-update",
    ),
    path("locations/", views.LocationListView.as_view(), name="location-list"),
    path(
        "location/<int:pk>/", views.LocationDetailView.as_view(), name="location-detail"
    ),
    path(
        "location/update/<int:pk>/",
        views.LocationUpdateView.as_view(),
        name="location-update",
    ),
    path(
        "location/create/",
        views.LocationCreateView.as_view(),
        name="location-create",
    ),
]

app/clients/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass


class Location(models.Model):
    name = models.CharField(max_length=50)

    # class Meta:
    #     verbose_name_plural = 'cities'

    def __str__(self):
        return self.name


class Client(models.Model):
    """
    Client model.
    """

    user = models.OneToOneField("User", on_delete=models.CASCADE)
    first_name = models.CharField(max_length=254, blank=True)
    last_name = models.CharField(max_length=254, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    location = models.ForeignKey(
        "Location", on_delete=models.SET_NULL, null=True, related_name="cities"
    )
    bio = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return f"/client/{self.id}"

    def get_full_name(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        return self.user.username


    def __str__(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        return self.user.username

app/clients/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Client, Location


class LocationListView(LoginRequiredMixin, ListView):
    model = Location


class LocationDetailView(LoginRequiredMixin, DetailView):
    model = Location


class LocationCreateView(LoginRequiredMixin, CreateView):
    model = Location
    fields = "__all__"


class LocationUpdateView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = "__all__"


class ClientListView(LoginRequiredMixin, ListView):
    model = Client


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = "__all__"

app/clients/templates/clients/client_detail.html
{% extends 'base.html' %}


{% block head_title %}
{{object}} -
{% endblock head_title %}



{% block content %}

<div class="container">

    <h1>{{object}}</h1>
    <hr>
    <div class="card"
        style="max-width: 28rem;">
        <div class="card-body">
            <h5 class="card-title">{{object.location}}</h5>
            <p class="card-text">{{object.phone}}</p>
            <hr>
            <a href="{% url 'clients:client-update' object.pk %}"
                class="btn btn-primary">Edit</a>
        </div>
    </div>

</div>

{% endblock content %}

app/clients/templates/clients/client_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}
{{object}} -
{% endblock head_title %}



{% block content %}

<div class="container">

    <form action="" method="post" style="max-width: 24rem;">
    {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-dark mt-3" type="submit">Update</button>
    </form>

</div>

{% endblock content %}

app/clients/templates/clients/client_list.html
{% extends 'base.html' %}


{% block head_title %}
Clients -
{% endblock head_title %}



{% block content %}

<div class="container">

    <ol>
        {% for object in object_list %}

        <li>
            <a href="{% url 'clients:client-detail' object.pk %}">
                {{object.get_full_name}}
            </a>
        </li>
        {% endfor %}

    </ol>


</div>

{% endblock content %}

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">

    <title>


        {% block head_title %}

        {% endblock head_title %}
        DataGrab
    </title>
</head>

<body>
    {% include 'header.html' %}
    {% block content %}

    {% endblock content %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/templates/header.html
<nav class="py-2 bg-light border-bottom">
        <div class="container d-flex flex-wrap">
                <ul class="nav me-auto">
                        <li class="nav-item"><a href="/"
                                        class="nav-link link-dark px-2 active"
                                        aria-current="page">Home</a></li>
                        <li class="nav-item"><a href="/"
                                        class="nav-link link-dark px-2">Clients</a>
                        </li>
                        <li class="nav-item"><a href="/"
                                        class="nav-link link-dark px-2">Pricing</a>
                        </li>
                        <li class="nav-item"><a href="#"
                                        class="nav-link link-dark px-2">FAQs</a>
                        </li>
                        <li class="nav-item"><a href="#"
                                        class="nav-link link-dark px-2">About</a>
                        </li>
                </ul>
                <ul class="nav">

                        {% if request.user.is_authenticated %}
                        <li class="nav-item"><a
                                        href="{% url 'clients:client-update' request.user.pk %}""
                class="
                                        nav-link
                                        link-dark
                                        px-2">Profile</a></li>
                        <li class="nav-item"><a
                                        href="{% url 'account_logout' %}"
                                        class="nav-link link-dark px-2">Logout</a>
                        </li>
                        {% else %}

                        <li class="nav-item"><a
                                        href="{% url 'account_login' %}"
                                        class="nav-link link-dark px-2">Login</a>
                        </li>
                        <li class="nav-item"><a
                                        href="{% url 'account_signup' %}"
                                        class="nav-link link-dark px-2">Sign
                                        up</a></li>


                        {% endif %}


                </ul>
        </div>
</nav>
<header class="py-3 mb-4 border-bottom">
        <div class="container d-flex flex-wrap justify-content-center">
                <a href="/"
                        class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
                        <svg class="bi me-2"
                                width="40"
                                height="32">
                                <use xlink:href="#bootstrap" />
                        </svg>
                        <span class="fs-4">Data Grab</span>
                </a>
                <form class="col-12 col-lg-auto mb-3 mb-lg-0">
                        <input type="search"
                                class="form-control"
                                placeholder="Search..."
                                aria-label="Search">
                </form>
        </div>
</header>